"""Add pollo_video_url and analysis_metadata to video_clips

Revision ID: f7a9c3e2b1d4
Revises: 3b13b7e838b7
Create Date: 2026-03-02 09:25:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a9c3e2b1d4'
down_revision = '3b13b7e838b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_clips', sa.Column('pollo_video_url', sa.String(length=1000), nullable=True))
    op.add_column('video_clips', sa.Column('analysis_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_clips', 'analysis_metadata')
    op.drop_column('video_clips', 'pollo_video_url')
    # ### end Alembic commands ###
